### ISSUE TITLE
Find some way to prioritize newly added welcome messages

### ISSUE THREAD

**Issue by CarrotManMatt** [CSSUoB/TeX-Bot-Py-V2#10]
The current system of selecting a welcome message when someone is inducted into the CSS Discord server is a random pick from the list of messages in the welcome_messages.json file. It has been discussed to allow members to add their own custom welcome messages. However, because these would just be added to the list of possible welcome messages, there is no guarantee that theirs will be shown.
Therefore, there should be a way to prioritise newly added welcome messages until after a certain time period has elapsed, at which point the selection process would return to being random. This could possibly be done by loading the welcome messages into a database?

**Comment by codemicro** [comment]
All of that said - instead of using a database, what about altering the `messages.json` schema to be like this?

```json
{
    "welcome_messages":
        "<User> just joined. Everyone, look busy!",
        ["<User> joined the CSS party.", "2023-08-22"],
    ]
}
```

In this example, the normal messages are just strings, but the prioritised messages are an array with a message and a date added. This way, you could then weight those messages higher for a certain amount of time (eg. 30 days) until dropping back down to normal like the rest.

**Comment by CarrotManMatt** [comment]
This is unnecessary & the list will just be updated to have higher quality messages

**Comment by CarrotManMatt** [comment]
This is unnecessary & the list will just be updated to have higher quality messages
