### ISSUE TITLE
403 Forbidden role reminders

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/TeX-Bot-Py-V2#204]
![image](https://github.com/CSSUoB/TeX-Bot-Py-V2/assets/18513864/17b6f865-755c-46ec-a79a-f914344d6692)

This issue is present in the get role reminders but it also occurs to me it could pop up in other areas too. 

Because it's not possible to check if a user has blocked the bot, or disabled DMs, we should have a unified way to handle the error of not being able to send a message to a user

**Comment by CarrotManMatt** [comment]
> a user has blocked the bot, or disabled DMs

Is that the leading theory on why the forbidden error is occurring?

**Comment by MattyTheHacker** [comment]
> > a user has blocked the bot, or disabled DMs
> 
> Is that the leading theory on why the forbidden error is occurring?

I can't say for certain but that's the only thing I can think of - everything else that it could be is being checked for in one way or another already so that's my guess

**Comment by CarrotManMatt** [comment]
Sure, a good theory as any. A try-except would then be suitable for this situation as there is no way to check for these conditions (See [this StackOverflow post](https://stackoverflow.com/a/72604423/14403974)).

However, I think it is essential that we only except for a `ForbiddenError` and perform an additional check to attempt to guess why that error was raised. If it was raised because of one of the mentioned conditions then a log message should be sent and the loop should continue to the next member, otherwise the error should continue to be raised if the reasoning for it was not known. This will help with future debugging if issues occur.
