### ISSUE TITLE
Stats leftmembers error

### ISSUE THREAD

**Issue by MattyTheHacker** [CSSUoB/TeX-Bot-Py-V2#227]
![image](https://github.com/CSSUoB/TeX-Bot-Py-V2/assets/18513864/a357fede-1591-4342-a660-e4039f6f03ff)

**Comment by CarrotManMatt** [comment]
What is the issue here? It is explaining that there haven't yet been enough roles captured of people that left the server to display a useful graph.

https://github.com/CSSUoB/TeX-Bot-Py-V2/blob/241f78ff0d4e4b51b1596bdb7b54d3c2bc47bff2/cogs/stats.py#L550

There has to be at least 15 data points to display a graph. Double check that there are at least 15 records in your deployment's database.
